language: node_js
node_js:
  - "5.7"
install:
  - npm install -g gulp
  - npm install -g firebase-tools
  - npm install
script:
  - gulp build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
